#!/usr/bin/env python3






























import argparse
import base64
import hashlib
import io
import os
import re
import sys
import time
import zipfile

MODULE_DIR_NAME = "modules"
MAIN_FILE_NAME = "IFMMaster.lua"
WORKER_FILE_NAME = "IFMWorker.lua"
CRAFTER_FILE_NAME = "IFMCrafter.lua"
DEFAULT_OUTPUT = "ifm_bundle.lua"
# 压缩载荷（默认）：vendored zzlib 负责在 CC:T 端解压 ZIP
VENDOR_DIR_NAME = "vendor/zzlib"
VENDOR_FILES = ("inflate-bit32.lua", "zzlib.lua")
VENDOR_NOTICE = "zzlib - WTFPL - (c) 2016-2026 Francois Galea - https://codeberg.org/zerkman/zzlib"
ARCHIVE_SEGMENT_CHARS = 1024

HEADER = """-- IFM (Integrated Factory Manager) single-file unpacker
-- Version: {version} (IFMMaster.lua / IFMWorker.lua / IFMCrafter.lua / frontend must all match)
-- Generated by build.py at {built_at}; do not edit manually
-- (edit IFMMaster.lua / modules/*.lua and rebuild). Fingerprint: {digest}
--
-- What it does (unpack only, no auto-start):
--   * creates an "ifm" directory next to this file and writes the embedded sources into it:
--       ifm/IFMMaster.lua    (server entry - start it yourself afterwards)
--       ifm/IFMWorker.lua    (worker entry)
--       ifm/IFMCrafter.lua   (turtle/robot crafter entry)
--       ifm/modules/*.lua    (modules; identical content is skipped)
--   * then deletes this bundle file itself
--     (unless this file is named IFMMaster.lua / IFMWorker.lua / IFMCrafter.lua, in which case it is kept).
--
-- The Lua sources travel as a single base64 ZIP payload; a vendored copy of zzlib
-- (WTFPL - see backend/vendor/zzlib/UPSTREAM.txt) inflates it on this computer.
--
-- Usage (CC:Tweaked computer):
--   ifm_bundle                     (run this file once)
--   then start the server with:    ifm/IFMMaster.lua [--room <room>] [--relay <ws-base-url>] [--random-room]
--   arguments given to the bundle are ignored.
"""

def read_text(path):
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()

VERSION_SITES = (
    ("modules/transfer.lua", r'(Transfer\.VERSION = ")([^"]+)(")'),
    ("IFMMaster.lua", r'(local IFM_VERSION = ")([^"]+)(")'),
    ("web/ifm-core.js", r"(IFM_CLIENT_VERSION = ')([^']+)(')"),
    ("web/ifm-app.js", r"(IFM_APP_BUILD = ')([^']+)(')"),
)

def repo_root(base_dir):
    return os.path.dirname(os.path.abspath(base_dir))

def site_path(base_dir, rel):
    if rel.startswith("web/"):
        return os.path.join(repo_root(base_dir), "frontend", rel.replace("/", os.sep))
    return os.path.join(base_dir, rel.replace("/", os.sep))

def read_required(path):
    if not os.path.isfile(path):
        raise SystemExit("找不到文件：%s（构建需要完整的 backend/ 与 frontend/）" % path)
    return read_text(path)

def parse_version(value):
    text = str(value).strip()
    if not re.fullmatch(r"\d+", text):
        raise SystemExit("版本号必须是单一整数（例如 --version 306），不再支持点分格式：%r" % value)
    return int(text)

def read_version(base_dir):
    repo = repo_root(base_dir)
    found = []
    legacy = []
    for rel, pattern in VERSION_SITES:
        path = site_path(base_dir, rel)
        match = re.search(pattern, read_required(path))
        if not match:
            raise SystemExit("找不到版本号：%s（期望形如 ... = \"12\" 的整数）" % path)
        raw = match.group(2)
        if re.fullmatch(r"\d+", raw):
            found.append((os.path.relpath(path, repo), int(raw)))
        else:
            legacy.append((os.path.relpath(path, repo), raw))
    index_path = os.path.join(repo, "frontend", "index.html")
    index = read_required(index_path)
    build = re.search(r'data-ifm-build="(\d+)"', index)
    if not build:
        raise SystemExit("找不到 data-ifm-build：%s" % index_path)
    tags = re.findall(r"\?v=(\d+)", index)
    if not tags:
        raise SystemExit("index.html 里找不到任何 ?v=<数字>：%s" % index_path)
    if len(set(tags) | {build.group(1)}) != 1:
        raise SystemExit("index.html 里的版本号不一致：data-ifm-build=%s，?v=%s"
                         % (build.group(1), ",".join(sorted(set(tags)))))
    found.append((os.path.relpath(index_path, repo), int(build.group(1))))
    for rel, raw in legacy:
        print("提示：%s 还是点分版本号 %s，本次构建会统一成整数" % (rel, raw))
    current = max(value for _, value in found)
    if len({value for _, value in found}) != 1:
        print("版本号不一致：%s —— 以最大值 %d 为准并统一写回"
              % ("、".join("%s=%d" % item for item in found), current))
    return current

def write_version(base_dir, version):
    repo = repo_root(base_dir)
    text = str(parse_version(version))
    for rel, pattern in VERSION_SITES:
        path = site_path(base_dir, rel)
        content = read_required(path)
        updated, count = re.subn(pattern, lambda match: match.group(1) + text + match.group(3), content)
        if count != 1:
            raise SystemExit("版本号写入失败（%s，匹配 %d 次）" % (path, count))
        if updated != content:
            with open(path, "w", encoding="utf-8", newline="") as handle:
                handle.write(updated)
    index_path = os.path.join(repo, "frontend", "index.html")
    index = read_required(index_path)
    updated, build_count = re.subn(r'data-ifm-build="\d+"', 'data-ifm-build="%s"' % text, index)
    if build_count != 1:
        raise SystemExit("data-ifm-build 写入失败（%s，匹配 %d 次）" % (index_path, build_count))
    updated, tag_count = re.subn(r"\?v=\d+", "?v=%s" % text, updated)
    if tag_count == 0:
        raise SystemExit("index.html 里的 ?v= 版本号写入失败：%s" % index_path)
    if updated != index:
        with open(index_path, "w", encoding="utf-8", newline="") as handle:
            handle.write(updated)
    print("版本号：%s（transfer.lua / IFMMaster.lua / ifm-core.js / ifm-app.js 各 1 处，"
          "index.html 的 data-ifm-build 与 %d 个 ?v=）" % (text, tag_count))
    return int(text)

def collect_files(base_dir):
    modules = []
    module_dir = os.path.join(base_dir, MODULE_DIR_NAME)
    if not os.path.isdir(module_dir):
        raise SystemExit("找不到模块目录：%s" % module_dir)
    for name in sorted(os.listdir(module_dir)):
        if not name.endswith(".lua"):
            continue
        path = os.path.join(module_dir, name)
        rel = "%s/%s" % (MODULE_DIR_NAME, name)
        modules.append((rel, read_text(path)))
    if not modules:
        raise SystemExit("模块目录中没有 .lua 文件：%s" % module_dir)
    main_path = os.path.join(base_dir, MAIN_FILE_NAME)
    if not os.path.isfile(main_path):
        raise SystemExit("找不到主程序：%s" % main_path)
    main_rel = MAIN_FILE_NAME
    return modules, (main_rel, read_text(main_path))

def collect_extra_entries(base_dir):


    out = []
    for name in (WORKER_FILE_NAME, CRAFTER_FILE_NAME):
        path = os.path.join(base_dir, name)
        if os.path.isfile(path):
            out.append((name, read_text(path)))
    return out

BOOTSTRAP_TEMPLATE = """
-- ===== Embedded sources: written into ./ifm/ (created next to this file) =====
{data}

-- 同一路径的两种写法（"a/b.lua" 与 "/a/b.lua"）视为相等
local __ifm_normalizePath = function(path)
    local value = fs.combine(path)
    if value:sub(1, 1) == "/" and #value > 1 then
        value = value:sub(2)
    end
    return value
end

local __ifm_unpack = function()
    local program = (shell and shell.getRunningProgram and shell.getRunningProgram()) or "{main}"
    --- 规范化后的自身路径：用来判断“正在运行的文件”是不是将要写入的那个（解包器自身/入口同名文件不覆盖）
    local programPath = __ifm_normalizePath(program)
    --- `wget run <url>` 时“正在运行的程序”在磁盘上并不存在（甚至可能是个 URL 字符串）：
    --- 这时就解包到 shell 的当前目录；本地运行则用产物自己所在目录，不拿不存在的路径去 fs.getDir
    local bundleDir
    if fs.exists(program) then
        bundleDir = fs.getDir(program)
    elseif shell and shell.dir then
        bundleDir = shell.dir()
    else
        bundleDir = fs.getDir(program)
    end
    if bundleDir == "" then
        bundleDir = "/"
    end
    --- 1.6.17 起：所有东西都写进 <产物目录>/ifm/（IFMMaster.lua / IFMWorker.lua / modules/）
    local baseDir = fs.combine(bundleDir, "ifm")
    if not fs.exists(baseDir) then
        fs.makeDir(baseDir)
        print("[IFM] created directory: " .. baseDir)
    end
    --- 先删掉自己再解压（CC:T 的磁盘很小）：产物本身约 190KB，和"解压出来的 20 个文件"同时存在
    --- 很容易超出磁盘容量（运行时报 out of space 而半途而废）。源码此刻已全部读进内存，
    --- 删掉磁盘上的产物文件不影响这次解压 —— 只是不能再"重跑一次解压"了（重新下载即可）。
    --- 注意：本产物被命名为 IFMMaster.lua / IFMWorker.lua / IFMCrafter.lua 时不删（它是入口本体）。
    local isEntryName = (programPath == "IFMMaster.lua" or programPath == "IFMWorker.lua"
        or programPath == "IFMCrafter.lua")
    if fs.exists(program) and not isEntryName then
        local removed, removeErr = pcall(fs.delete, program)
        if removed then
            print("[IFM] unpacker deleted first (frees disk space before unpacking): " .. program)
        else
            print("[IFM] note: could not delete the unpacker now (" .. tostring(removeErr) ..
                ") - unpacking anyway")
        end
    end
    --- 单个文件的写入与“内容相同则跳过”：两种载荷（zip / 明文）共用这一段
    local stats = {{ created = 0, updated = 0, unchanged = 0, skipped = 0 }}
    local __ifm_write = function(relative, content)
        local path = fs.combine(baseDir, relative)
        if __ifm_normalizePath(path) == programPath then
            -- do not overwrite the file that is currently running
            stats.skipped = stats.skipped + 1
            return
        end
        local folder = fs.getDir(path)
        if folder ~= "" and not fs.exists(folder) then
            fs.makeDir(folder)
        end
        local current = nil
        if fs.exists(path) then
            local handle = fs.open(path, "r")
            if handle then
                current = handle.readAll()
                handle.close()
            end
        end
        if current == content then
            stats.unchanged = stats.unchanged + 1
            return
        end
        local handle = fs.open(path, "w")
        if not handle then
            error("Cannot write " .. path, 0)
        end
        handle.write(content)
        handle.close()
        if current then
            stats.updated = stats.updated + 1
        else
            stats.created = stats.created + 1
        end
    end
{loop}
    print(("[IFM] unpack: %d created, %d updated, %d unchanged, %d skipped"):format(
        stats.created, stats.updated, stats.unchanged, stats.skipped))
    print("[IFM] entry file: " .. fs.combine(baseDir, "{main}"))
    print("[IFM] start the server with: " .. fs.combine(baseDir, "{main}"))
    return baseDir
end

-- ===== 解压（本产物只解压，不会自启服务端） =====
local __ifm_base = __ifm_unpack()
{cleanup}

if select("#", ...) > 0 then
    print("[IFM] note: this bundle only unpacks; arguments are ignored (pass them to IFMMaster.lua)")
end

-- ===== 解压完成后删除本产物自身 =====
local __ifm_self = (shell and shell.getRunningProgram and shell.getRunningProgram()) or nil
local __ifm_entry = __ifm_normalizePath(fs.combine(__ifm_base, "{main}"))
local __ifm_worker = __ifm_normalizePath(fs.combine(__ifm_base, "{worker}"))
local __ifm_crafter = __ifm_normalizePath(fs.combine(__ifm_base, "{crafter}"))
if __ifm_self == nil then
    print("[IFM] warning: cannot locate this file, please delete it manually")
elseif not fs.exists(__ifm_self) then
    -- `wget run <url>` / `pastebin run ...` 这类“直接从 URL 跑”的情况：磁盘上根本没有这个文件，
    -- 没有东西可删（也不要打印“删不掉”的警告）。（1.6.13）
    print("[IFM] nothing to delete now (run from a URL, or already removed before unpacking)")
elseif __ifm_normalizePath(__ifm_self) == __ifm_entry
    or __ifm_normalizePath(__ifm_self) == __ifm_worker
    or __ifm_normalizePath(__ifm_self) == __ifm_crafter then
    -- 本产物被命名为入口文件名（IFMMaster.lua / IFMWorker.lua / IFMCrafter.lua）：它就是入口本体
    print("[IFM] this file is named {main} / {worker} / {crafter}, keeping it (it is an entry point)")
else
    local okDelete, deleteErr = pcall(fs.delete, __ifm_self)
    if okDelete then
        print("[IFM] unpacker deleted: " .. fs.combine(__ifm_self))
    else
        print("[IFM] warning: could not delete " .. fs.combine(__ifm_self) .. " (" .. tostring(deleteErr) .. ")")
    end
end

print("[IFM] unpack finished - the server was NOT started by this file.")
print("[IFM] start it with: {main} [--room <room>] [--relay <ws-base-url>] [--random-room]")
"""

def vendor_dir_path(base_dir):
    return os.path.join(base_dir, *VENDOR_DIR_NAME.split("/"))

def read_vendor(base_dir):
    directory = vendor_dir_path(base_dir)
    missing = [name for name in VENDOR_FILES if not os.path.isfile(os.path.join(directory, name))]
    if missing:
        raise SystemExit("缺少 vendored zzlib 文件：%s（见 %s/UPSTREAM.txt）" %
                         (", ".join(missing), directory))
    out = {}
    for name in VENDOR_FILES:
        with open(os.path.join(directory, name), "r", encoding="utf-8", newline="\n") as handle:
            text = handle.read()
        try:
            text.encode("ascii")
        except UnicodeEncodeError:
            raise SystemExit("vendored 文件必须是纯 ASCII（CC:T 端原样执行）：%s" % name)
        out[name] = text
    return out

def render_archive(files):
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for rel, content in files:
            archive.writestr(rel, content.encode("utf-8"))
    blob = buffer.getvalue()
    encoded = base64.b64encode(blob).decode("ascii")
    with zipfile.ZipFile(io.BytesIO(blob)) as check:
        names = check.namelist()
        expected = [rel for rel, _ in files]
        if names != expected:
            raise SystemExit("载荷自检失败：ZIP 条目与源码不一致（%s）" % names)
        for rel, content in files:
            if check.read(rel) != content.encode("utf-8"):
                raise SystemExit("载荷自检失败：ZIP 内容与源码不一致：%s" % rel)
    print("载荷自检：ZIP 内 %d 个文件与源码逐字节一致（%d 字节 -> base64 %d 字符）" %
          (len(files), len(blob), len(encoded)))
    segments = [encoded[i:i + ARCHIVE_SEGMENT_CHARS]
                for i in range(0, len(encoded), ARCHIVE_SEGMENT_CHARS)]
    lines = ["local __IFM_ARCHIVE = table.concat({"]
    for segment in segments:
        lines.append("[[%s]]," % segment)
    lines.append("})")
    return "\n".join(lines) + "\n", len(blob), len(encoded)

def render_vendor(base_dir):
    vendor = read_vendor(base_dir)
    parts = [VENDOR_PRELUDE.replace("__VENDOR_NOTICE__", VENDOR_NOTICE)]
    parts.append("\n-- ===== vendored zzlib: inflate-bit32.lua (upstream, verbatim) =====\n")
    parts.append("local __IFM_INFLATE = (function()\n")
    parts.append(vendor["inflate-bit32.lua"])
    parts.append("\nend)()\n")
    parts.append("\n-- ===== vendored zzlib: zzlib.lua (upstream, verbatim; require() injected) =====\n")
    parts.append("local __IFM_ZZLIB = (function()\n")
    parts.append(ZZLIB_REQUIRE_SHIM)
    parts.append(vendor["zzlib.lua"])
    parts.append("\nend)()\n")
    parts.append(ZIP_ARCHIVE_READER)
    return "".join(parts)

VENDOR_PRELUDE = """
-- ===== Archive payload + vendored zzlib =====
-- Payload: one ZIP archive (deflate) carried as base64 text and unpacked on the
-- CC:T side by zzlib. Upstream revision: vendor/zzlib/UPSTREAM.txt
-- __VENDOR_NOTICE__
-- Both vendored sources are embedded verbatim; only the loader below
-- (base64 decoder, require injection) belongs to this project.
local __ifm_b64alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local __ifm_b64map = {}
for __ifm_i = 1, #__ifm_b64alpha do
    __ifm_b64map[__ifm_b64alpha:byte(__ifm_i)] = __ifm_i - 1
end
local __ifm_pow2 = { [0] = 1 }
for __ifm_i = 1, 32 do
    __ifm_pow2[__ifm_i] = __ifm_pow2[__ifm_i - 1] * 2
end

local function __ifm_b64decode(text)
    if type(text) ~= "string" then
        return nil, "archive payload is missing"
    end
    local out, count, acc, bits = {}, 0, 0, 0
    for i = 1, #text do
        local code = __ifm_b64map[text:byte(i)]
        if code then
            acc = acc * 64 + code
            bits = bits + 6
            if bits >= 8 then
                bits = bits - 8
                count = count + 1
                out[count] = string.char(math.floor(acc / __ifm_pow2[bits]) % 256)
                acc = acc % __ifm_pow2[bits]
            end
        end
    end
    if count == 0 then
        return nil, "archive payload is empty"
    end
    return table.concat(out)
end

-- zzlib uses the bit32 (Lua 5.2) or bit (LuaJIT) library. There is no fallback:
-- a runtime that provides neither cannot unpack this bundle.
assert(bit32 or bit,
    "[IFM] this runtime provides neither bit32 nor bit - the bundle cannot be unpacked")

-- One diagnostic line: CC:Tweaked (Lua 5.2 / Cobalt) ships bit32, which is the only
-- supported path.
print(("[IFM] unpacker runtime: %s, bit library: %s, payload: %d base64 chars"):format(
    _VERSION or "?", (bit32 and "bit32") or (bit and "bit") or "none",
    #(__IFM_ARCHIVE or "")))
"""

ZZLIB_REQUIRE_SHIM = """    -- zzlib selects its backend through _VERSION; both names resolve to the
    -- vendored inflate-bit32 implementation, so no filesystem require() is used.
    local require = function(name)
        if name == "inflate-bit32" or name == "inflate-bwo" then
            return __IFM_INFLATE
        end
        error("zzlib: unsupported module '" .. tostring(name) .. "'", 0)
    end
"""

ZIP_ARCHIVE_READER = """
-- Decode the base64 payload into the ZIP bytes that zzlib reads from.
local function __ifm_archive()
    local text = __IFM_ARCHIVE
    __IFM_ARCHIVE = nil
    return __ifm_b64decode(text)
end
"""

ZIP_LOOP = """    local __ifm_zip, __ifm_zipError = __ifm_archive()
    if not __ifm_zip then
        error("archive payload unavailable: " .. tostring(__ifm_zipError), 0)
    end
    for _, relative, offset, size, packed, crc in __IFM_ZZLIB.files(__ifm_zip) do
        if packed then
            -- zzlib verifies the CRC32 of every packed entry; a mismatch aborts
            -- the whole unpack instead of leaving a half-written file behind.
            local okUnzip, data = pcall(__IFM_ZZLIB.unzip, __ifm_zip, offset, crc)
            if not okUnzip then
                error("cannot unpack " .. relative .. ": " .. tostring(data), 0)
            end
            __ifm_write(relative, data)
        else
            __ifm_write(relative, __ifm_zip:sub(offset, offset + size - 1))
        end
    end
"""

def load_ascii_checker():




    here = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(here, "tools"),
        os.path.join(os.path.dirname(here), "tools"),
        os.path.join(os.path.dirname(os.path.dirname(here)), "tools"),
    ]
    for tools_dir in candidates:
        if os.path.isfile(os.path.join(tools_dir, "ascii_source.py")):
            if tools_dir not in sys.path:
                sys.path.insert(0, tools_dir)
            import ascii_source
            return ascii_source
    raise SystemExit("找不到检查工具 tools/ascii_source.py（已尝试：%s）" % "、".join(candidates))

BASE_DIR_HACK = [os.path.dirname(os.path.abspath(__file__))]

LUA_KEYWORDS = (
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
    "if", "in", "local", "nil", "not", "or", "repeat", "return", "then",
    "true", "until", "while",
)
KEYWORD_FIELD_PATTERNS = (
    ("字段访问 t.<关键字>", re.compile(r"\.\s*(%s)\b" % "|".join(LUA_KEYWORDS))),
    ("表键 { <关键字> =", re.compile(r"[,{]\s*(%s)\s*=" % "|".join(LUA_KEYWORDS))),
)
STRING_LITERAL = re.compile(r"\"(\\\\.|[^\"\\\\])*\"|'(\\\\.|[^'\\\\])*'")

METHOD_DEF = re.compile(r"^\s*function\s+([A-Za-z0-9_]+)\s*[:.]\s*([A-Za-z0-9_]+)\s*\(")
FIELD_ASSIGN = re.compile(r"^\s*([A-Za-z0-9_.]+)\s*\.\s*([A-Za-z0-9_]+)\s*=(?!=)")

def run_method_shadow_check(files):
    methods, owners = {}, {}
    for rel, content in files:
        for line in content.splitlines():
            match = METHOD_DEF.match(line)
            if not match:
                continue
            class_name, method = match.group(1), match.group(2)
            methods.setdefault(class_name, set()).add(method)
            owners.setdefault(rel, set()).add(class_name)
    problems = []
    for rel, content in files:
        local_classes = owners.get(rel, set())
        for index, line in enumerate(content.splitlines(), 1):
            match = FIELD_ASSIGN.match(line.split("--")[0])
            if not match:
                continue
            target, field = match.group(1), match.group(2)
            last = target.split(".")[-1]
            if last == "self":
                candidates = local_classes
            else:
                candidates = set(name for name in methods if name.lower() == last.lower())
            for class_name in candidates:
                if field in methods.get(class_name, ()):
                    problems.append("  %s:%d  %s.%s 会覆盖 %s:%s()：%s" % (
                        rel, index, target, field, class_name, field, line.strip()[:90]))
    if problems:
        raise SystemExit(
            "构建中止：实例字段与类方法重名（运行时会报 attempt to call method 'x'）。\n"
            "请给字段改名（例如 perf -> perfStats、stats -> statsSummary）：\n" + "\n".join(problems)
        )
    print("方法遮蔽检查：通过（%d 个 Lua 文件，没有实例字段覆盖类方法）" % len(files))
    return files

LUA_METHOD_CALL = re.compile(r":\s*([A-Za-z_][A-Za-z_0-9]*)(?![A-Za-z_0-9])\s*(?![({}\"'])" + r"(?![A-Za-z_0-9])")

def strip_lua_code(content):
    out = []
    problems = []
    i = 0
    n = len(content)
    while i < n:
        match = re.match(r"\[(=*)\[", content[i:])
        if match:
            level = len(match.group(1))
            closer = "]" + "=" * level + "]"
            j = content.find(closer, i)
            j = n if j < 0 else j + len(closer)
            out.append("".join(" " if ch != "\n" else "\n" for ch in content[i:j]))
            i = j
            continue
        if content.startswith("--", i):
            j = content.find("\n", i)
            j = n if j < 0 else j
            out.append(" " * (j - i))
            i = j
            continue
        ch = content[i]
        if ch in "\"'":
            j = i + 1
            terminated = False
            while j < n:
                if content[j] == "\\":
                    j += 2
                    continue
                if content[j] == ch:
                    terminated = True
                    j += 1
                    break
                if content[j] == "\n":
                    break
                j += 1
            if not terminated:
                problems.append(("string", content.count("\n", 0, i) + 1, content[i:i + 60].split("\n")[0]))
            out.append(" " * (j - i))
            i = j
            continue
        out.append(ch)
        i += 1
    return "".join(out), problems

def run_lua_structure_check(files):
    problems = []
    for rel, content in files:
        code, string_problems = strip_lua_code(content)
        for _, number, text in string_problems:
            problems.append("  %s:%d  字符串没有收尾：%s" % (rel, number, text.strip()[:60]))
        for match in LUA_METHOD_CALL.finditer(code):
            number = code.count("\n", 0, match.start()) + 1
            problems.append("  %s:%d  `:%s` 后面缺少调用参数（Lua 会报 function arguments expected）：%s"
                            % (rel, number, match.group(1),
                               code.split("\n")[number - 1].strip()[:80]))
        depth = 0
        for number, line in enumerate(code.split("\n"), 1):
            for word in re.findall(r"[A-Za-z_][A-Za-z_0-9]*", line):
                if word in ("function", "if", "do", "repeat"):
                    depth += 1
                elif word in ("end", "until"):
                    depth -= 1
                    if depth < 0:
                        problems.append("  %s:%d  多出来的 `end`（块结构已经回到顶层）：%s"
                                        % (rel, number, line.strip()[:80]))
                        depth = 0
        if depth != 0:
            problems.append("  %s  块结构不平衡：还差 %d 个 `end`/`until`" % (rel, depth))
    if problems:
        raise SystemExit(
            "构建中止：Lua 语法检查发现问题（这些错误只有真正 load 时才会暴露）。\n"
            "常见修法：`self:foo and x` -> `self.foo and self:foo()`；补齐/删掉多余的 end。\n"
            + "\n".join(problems)
        )
    print("Lua 结构检查：通过（%d 个 Lua 文件：方法调用参数 / 块结构 / 字符串收尾；建议装 luaparse 做完整语法检查）"
          % len(files))
    return files

LUAPARSE_RUNNER = r"""
const fs = require('fs');
const luaparse = require('luaparse');
const entries = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
let problems = 0;
for (const entry of entries) {
    try {
        luaparse.parse(entry.code, { luaVersion: '5.1', locations: true, comments: false, scope: false });
    } catch (err) {
        problems += 1;
        const line = err.line === undefined ? '?' : err.line;
        const message = String(err.message || err).split('\n')[0];
        console.log('  ' + entry.rel + ':' + line + '  ' + message);
    }
}
process.exit(problems ? 1 : 0);
"""

LUAPARSE_LAST_ERROR = [""]
LUAPARSE_ENV = [None]

def luaparse_env(base_dir):




    import os as _os

    env = dict(_os.environ)
    extra = [_os.path.join(base_dir, "node_modules"), _os.path.join(_os.path.dirname(base_dir), "node_modules")]
    try:
        import subprocess
        root = subprocess.run(["npm", "root", "-g"], capture_output=True, text=True, timeout=60)
        if root.returncode == 0 and root.stdout.strip():
            extra.append(root.stdout.strip())
    except Exception:
        pass
    env["NODE_PATH"] = _os.pathsep.join([p for p in extra if p] + [env.get("NODE_PATH", "")])
    return env

def luaparse_available(base_dir):

    import subprocess

    env = luaparse_env(base_dir)
    try:
        result = subprocess.run(
            ["node", "-e", "process.stdout.write(require.resolve('luaparse'))"],
            cwd=base_dir, capture_output=True, text=True, timeout=120, env=env)
        if result.returncode == 0:
            LUAPARSE_ENV[0] = env
            return True
        LUAPARSE_LAST_ERROR[0] = (result.stderr or result.stdout or "").strip().splitlines()[-1][:160]
        return False
    except Exception as err:
        LUAPARSE_LAST_ERROR[0] = str(err)[:160]
        return False

def run_lua_syntax_check(files, base_dir=None):
    import json
    import os as _os
    import subprocess
    import tempfile

    base_dir = base_dir or BASE_DIR_HACK[0]
    if not luaparse_available(base_dir):
        print("提示：没有找到 Node 模块 luaparse（原因：%s）——执行 npm install --prefix backend luaparse "
              "可启用完整 Lua 语法检查；本次退回轻量结构检查。" % (LUAPARSE_LAST_ERROR[0] or "unknown"))
        return run_lua_structure_check(files)

    runner_path = _os.path.join(tempfile.gettempdir(), "ifm_luaparse_check.js")
    payload_path = _os.path.join(tempfile.gettempdir(), "ifm_luaparse_files.json")
    with open(runner_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(LUAPARSE_RUNNER)
    with open(payload_path, "w", encoding="utf-8") as handle:
        json.dump([{"rel": rel, "code": content} for rel, content in files], handle)
    try:
        result = subprocess.run(["node", runner_path, payload_path],
                                cwd=base_dir, capture_output=True, text=True, timeout=600,
                                env=LUAPARSE_ENV[0] or luaparse_env(base_dir))
    except Exception as err:
        print("提示：luaparse 调用失败（%s），退回轻量结构检查。" % err)
        return run_lua_structure_check(files)
    if result.returncode != 0:
        details = (result.stdout or "").strip() or (result.stderr or "").strip() or "(没有输出)"
        raise SystemExit(
            "构建中止：Lua 语法检查失败（luaparse，Lua 5.1 文法 = CC:T 用的 Lua）。\n"
            "这些错误在 CC:T 里 load 时同样会报，请按行号修好再构建：\n" + details)
    print("Lua 语法检查：通过（luaparse，%d 个文件）" % len(files))
    return files

LOCAL_LIST_DECL = re.compile(r"^local\s+([A-Za-z_][A-Za-z_0-9]*(?:\s*,\s*[A-Za-z_][A-Za-z_0-9]*)*)\s*(?:=|$)",
                             re.MULTILINE)
LOCAL_FUNC_DECL = re.compile(r"^local\s+function\s+([A-Za-z_][A-Za-z_0-9]*)", re.MULTILINE)
FUNCTION_PARAMS = re.compile(r"\bfunction\b[^(\n]*\(([^)]*)\)")
FOR_VARIABLES = re.compile(r"^\s*for\s+(.+?)\s+(?:in\b|=)")
IDENTIFIER_ONLY = re.compile(r"^[A-Za-z_][A-Za-z_0-9]*$")

def collect_bound_names(content):
    bound = set()
    code = STRING_LITERAL.sub('""', content)
    for match in FUNCTION_PARAMS.finditer(code):
        for name in match.group(1).split(","):
            name = name.strip()
            if IDENTIFIER_ONLY.match(name):
                bound.add(name)
    for match in FOR_VARIABLES.finditer(code):
        for name in match.group(1).split(","):
            name = name.strip()
            if IDENTIFIER_ONLY.match(name):
                bound.add(name)
    return bound

def run_local_order_check(files):
    problems = []
    for rel, content in files:
        lines = content.splitlines()
        bound = collect_bound_names(content)
        declarations = {}
        for index, line in enumerate(lines, 1):
            code = STRING_LITERAL.sub('""', line).split("--")[0]
            match = LOCAL_FUNC_DECL.match(code)
            if match:
                declarations.setdefault(match.group(1), index)
            match = LOCAL_LIST_DECL.match(code)
            if match:
                for name in match.group(1).split(","):
                    name = name.strip()
                    if name and name not in declarations:
                        declarations[name] = index
        for name, first in declarations.items():
            if name in bound:
                continue
            pattern = re.compile(r"(?<![A-Za-z0-9_.:])%s\s*[:.\[(]" % re.escape(name))
            for index, line in enumerate(lines, 1):
                if index >= first:
                    break
                code = STRING_LITERAL.sub('""', line).split("--")[0]
                if pattern.search(code):
                    problems.append("  %s:%d  先用后声明：`%s`（它到第 %d 行才 local）"
                                    % (rel, index, name, first))
                    break
    if problems:
        raise SystemExit(
            "构建中止：文件级局部变量在声明之前就被使用（Lua 会把它当全局，运行时是 nil：\n"
            "attempt to index global 'x' (a nil value)）。\n"
            "修法：把这个 local 声明挪到第一次使用之前（一般放在文件上方的状态区）：\n"
            + "\n".join(problems))
    print("定义顺序检查：通过（%d 个 Lua 文件，没有“先用后声明”的文件级局部变量）" % len(files))
    return files

def run_local_order_check(files):




    problems = []
    for rel, content in files:
        lines = content.splitlines()
        declarations = {}
        for index, line in enumerate(lines, 1):
            code = STRING_LITERAL.sub('""', line).split("--")[0]
            match = LOCAL_FUNC_DECL.match(code)
            if match:
                declarations.setdefault(match.group(1), []).append(index)
            match = LOCAL_LIST_DECL.match(code)
            if match:
                for name in match.group(1).split(","):
                    name = name.strip()
                    if name:
                        declarations.setdefault(name, []).append(index)
        for name, numbers in declarations.items():
            first = numbers[0]
            pattern = re.compile(r"(?<![A-Za-z0-9_.:])%s\s*[:.\[(]" % re.escape(name))
            for index, line in enumerate(lines, 1):
                if index >= first:
                    break
                code = STRING_LITERAL.sub('""', line).split("--")[0]
                if pattern.search(code):
                    problems.append("  %s:%d  先用后声明：`%s`（它到第 %d 行才 local）"
                                    % (rel, index, name, first))
                    break
    if problems:
        raise SystemExit(
            "构建中止：局部变量在声明之前就被使用（Lua 会把它当全局，运行时是 nil：\n"
            "attempt to index global 'x' (a nil value)）。\n"
            "修法：把这个 local 声明挪到第一次使用之前（一般放在文件上方的状态区）：\n"
            + "\n".join(problems))
    print("定义顺序检查：通过（%d 个 Lua 文件，没有“先用后声明”的局部变量）" % len(files))
    return files

def run_reserved_word_check(files):
    problems = []
    for rel, content in files:
        for index, line in enumerate(content.splitlines(), 1):
            code = line.split("--")[0]
            code = STRING_LITERAL.sub('""', code)
            for label, pattern in KEYWORD_FIELD_PATTERNS:
                if pattern.search(code):
                    problems.append("  %s:%d  %s：%s" % (rel, index, label, line.strip()[:100]))
    if problems:
        raise SystemExit(
            "构建中止：Lua 保留字被当成字段名/表键（Lua 5.1 语法错误，CC:T 会报 unexpected symbol）。\n"
            "请改名（例如 local -> localMoves）：\n" + "\n".join(problems)
        )
    print("保留字检查：通过（%d 个 Lua 文件，没有把保留字当字段名/表键）" % len(files))
    return files

# Globals the CC:Tweaked / Cobalt runtime provides (plus the Lua standard library).
LUA_GLOBALS = {
    "_G", "_VERSION", "assert", "bit", "bit32", "colours", "colors", "commands",
    "coroutine", "debug", "disk", "error", "fs", "getmetatable", "gps", "help",
    "http", "ipairs", "keys", "math", "multishell", "next", "os", "package",
    "paintutils", "pairs", "parallel", "pcall", "peripheral", "pocket", "print",
    "rawequal", "rawget", "rawlen", "rawset", "read", "rednet", "redstone",
    "require", "select", "setmetatable", "settings", "shell", "sleep", "string",
    "table", "term", "textutils", "tonumber", "tostring", "turtle", "type",
    "unpack", "vector", "window", "write", "xpcall",
}

LUA_LOCAL_DECL = re.compile(
    r"\blocal\s+(?!function\b)([A-Za-z_][A-Za-z0-9_]*(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)")
LUA_PARAM_LIST = re.compile(r"\bfunction\s*[A-Za-z_0-9.:]*\s*\(([^)]*)\)")
LUA_FOR_DECL = re.compile(
    r"\bfor\s+([A-Za-z_][A-Za-z0-9_]*(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)\s*(?:=|in)\b")
LUA_METHOD_DEF = re.compile(r"\bfunction\s+[A-Za-z_0-9]+\s*:\s*[A-Za-z_0-9]+\s*\(")
LUA_GLOBAL_WRITE = re.compile(
    r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\]|\.\s*[A-Za-z_][A-Za-z0-9_]*)?\s*=(?!=)")


def run_global_write_check(files):
    """An identifier that is only ever *assigned* cannot stay undeclared.

    Writing to a name that is neither a `local` of that file nor a runtime global
    silently creates a global. Reading it back before the write (or after the
    declaration was deleted) then fails at runtime with
    "attempt to index global 'x' (a nil value)" - exactly the class of crash this
    check exists to catch at build time.
    """
    problems = []
    for rel, content in files:
        raw, _string_problems = strip_lua_code(content)
        code = STRING_LITERAL.sub('""', raw)
        declared = set()
        for match in LUA_LOCAL_DECL.finditer(code):
            for name in match.group(1).split(","):
                declared.add(name.strip())
        # Function parameters are locals too (assigning to `opts` is not a global).
        for match in LUA_PARAM_LIST.finditer(code):
            for name in match.group(1).split(","):
                declared.add(name.strip())
        # Loop variables and the implicit `self` of `function Class:method()`.
        for match in LUA_FOR_DECL.finditer(code):
            for name in match.group(1).split(","):
                declared.add(name.strip())
        if LUA_METHOD_DEF.search(code):
            declared.add("self")
        depth = 0
        for index, line in enumerate(code.splitlines(), 1):
            # Inside a table constructor `name = value` is a *field*, not a global
            # write: only look at statement level (brace depth 0).
            if depth == 0:
                match = LUA_GLOBAL_WRITE.match(line)
                if match:
                    name = match.group(1)
                    if name not in declared and name not in LUA_GLOBALS and name not in (
                            "end", "then", "else", "elseif", "do", "if", "for", "while",
                            "repeat", "until", "function", "local", "return", "break"):
                        problems.append("  %s:%d  %s" % (rel, index, name))
            depth += line.count("{") - line.count("}")
    if problems:
        raise SystemExit(
            "构建中止：赋值给未声明的全局变量（Lua 会静默创建全局；读回时是 nil，"
            "运行时报 attempt to index global 'x'）。\n"
            "修法：在该文件上方声明 local，或删掉这处残留引用：\n" + "\n".join(sorted(set(problems)))
        )
    print("全局变量检查：通过（%d 个 Lua 文件，没有未声明的全局赋值）" % len(files))
    return files

# Calls whose *result can be nil* (documented behaviour: "unknown / not read yet").
# Using such a result directly as an arithmetic operand is the classic master crash
# ("attempt to perform arithmetic on a nil value") because the value is only nil while
# the scan is still incomplete - i.e. exactly during warm-up, minutes after startup.
NIL_CAPABLE_CALLS = (
    "slotCapacityFor",
    "slotStackCount",
    "slotLimitOf",
    "itemMaxCount",
    "slotCount",
)

CALL = r"(?:[A-Za-z_][A-Za-z0-9_]*\s*[.:]\s*)?(?:%s)\s*\(" % "|".join(NIL_CAPABLE_CALLS)
NIL_CALL_BEFORE_OPERATOR = re.compile(CALL + r"[^()]*(?:\([^()]*\)[^()]*)*\)\s*(?:[-+*/%%])(?!=)")
NIL_CALL_AFTER_OPERATOR = re.compile(r"[-+*/%%]\s*" + CALL)


def run_nil_call_arithmetic_check(files):
    """No arithmetic directly on a call whose result may be nil.

    These helpers return nil for "not read yet" on purpose (so nothing gets moved based
    on a guessed capacity). Every caller has to test the value first, e.g.
    `local cap = self:slotCapacityFor(...) ; if cap then ... end`.
    """
    problems = []
    for rel, content in files:
        raw, _ = strip_lua_code(content)
        code = STRING_LITERAL.sub('""', raw)
        for index, line in enumerate(code.splitlines(), 1):
            if line.lstrip().startswith("--"):
                continue
            if NIL_CALL_BEFORE_OPERATOR.search(line) or NIL_CALL_AFTER_OPERATOR.search(line):
                problems.append("  %s:%d  %s" % (rel, index, line.strip()))
    if problems:
        raise SystemExit(
            "构建中止：直接对可能为 nil 的调用结果做算术（运行时会崩主控：attempt to perform "
            "arithmetic on a nil value）。\n"
            "这些函数在“还没读到”时返回 nil：%s。\n"
            "修法：先取到局部变量并判空，例如 local cap = self:slotCapacityFor(...) ; "
            "if cap then ... end：\n%s"
            % (", ".join(NIL_CAPABLE_CALLS), "\n".join(sorted(set(problems))))
        )
    print("nil 算术检查：通过（%d 个 Lua 文件，没有对可能为 nil 的调用结果直接做算术）"
          % len(files))
    return files


HARD_DEPENDENCY = re.compile(
    r"needs the ([a-z0-9_]+) module:\s*pass opts\.([A-Za-z0-9_]+)\s*\(loadModule\(\\?\"([a-z0-9_]+)\\?\"\)\)")
LOAD_MODULE_BINDING = re.compile(
    r"local\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*loadModule\(\s*\"([A-Za-z0-9_]+)\"\s*\)")
NEW_CALL = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*\.\s*new\s*\(")

def call_arguments(code, open_paren):
    depth = 0
    index = open_paren
    size = len(code)
    while index < size:
        char = code[index]
        if char in "\"'":
            index = scan_short_string(code, index)
            continue
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return code[open_paren + 1:index]
        index += 1
    return code[open_paren + 1:]

def hard_dependencies(files):
    required = {}
    for rel, content in files:
        name = os.path.splitext(os.path.basename(rel))[0]
        for match in HARD_DEPENDENCY.finditer(strip_comments(content)):
            pairs = required.setdefault(name, [])
            entry = (match.group(1), match.group(2))
            if entry not in pairs:
                pairs.append(entry)
    return required

def option_argument(key):
    return re.compile(r"(?<![A-Za-z0-9_])%s\s*=(?!=)" % re.escape(key))

def run_hard_dependency_check(files):
    required = hard_dependencies(files)
    if not required:
        print("硬依赖检查：通过（没有声明 \"needs the ... module\" 的模块）")
        return files
    problems = []
    injected = {}
    for rel, content in files:
        code = strip_comments(content)
        bindings = {}
        for match in LOAD_MODULE_BINDING.finditer(code):
            bindings[match.group(1)] = match.group(2)
        for match in NEW_CALL.finditer(code):
            variable = match.group(1)
            module_name = bindings.get(variable)
            if module_name is None or module_name not in required:
                continue
            arguments = call_arguments(code, match.end() - 1)
            line = code.count("\n", 0, match.start()) + 1
            for dep, key in required[module_name]:
                if option_argument(key).search(arguments):
                    injected[(module_name, dep)] = injected.get((module_name, dep), 0) + 1
                    continue
                problems.append("  %s:%d  %s.new(...) 没有注入 opts.%s"
                                "（%s.lua 里写着 \"needs the %s module\"）"
                                % (rel, line, variable, key, module_name, dep))
    for module_name in sorted(required):
        for dep, key in required[module_name]:
            if not injected.get((module_name, dep)):
                problems.append("  %s.lua 声明了 \"needs the %s module\"，"
                                "但没有任何 X.new(...) 构造点注入 opts.%s（装配漏了？）"
                                % (module_name, dep, key))
    if problems:
        raise SystemExit(
            "构建中止：模块声明了硬依赖，就必须在每个构造点显式注入对应的 opts 键。\n"
            "漏注入的后果是**后端一启动就 error**（模块里那条硬断言，不是可以兜底的业务状态）：\n"
            + "\n".join(problems)
            + "\n修法：在 loadModule(\"x\") 之后，构造语句里补上 `Key = X,`"
              "（例如 Dispatch.new({ Assert = Assert, Queue = Queue, ... })）")
    proof = ["%s->%s" % (name, dep) for name in sorted(required) for dep, _ in required[name]]
    print("硬依赖检查：通过（%d 个模块声明了硬依赖：%s；共 %d 个构造点都注入了 opts 键）"
          % (len(required), "、".join(proof), sum(injected.values())))
    return files

def run_tools_check(base_dir):






    tool_dir = os.path.join(base_dir, "tools")
    if not os.path.isdir(tool_dir):
        return
    files = [("tools/" + name, read_text(os.path.join(tool_dir, name)))
             for name in sorted(os.listdir(tool_dir)) if name.endswith(".lua")]
    if not files:
        return
    ascii_source = load_ascii_checker()
    problems = []
    for rel, content in files:
        bad = ascii_source.find_violations(content)
        if not bad:
            continue
        problems.append("%s: %d 处非 ASCII（代码/字符串）" % (rel, len(bad)))
        for line, col, ch, kind in bad[:5]:
            problems.append("    第 %d 行第 %d 列 [%s] %r" % (line, col, ch, kind))
        if len(bad) > 5:
            problems.append("    ...（其余 %d 处省略）" % (len(bad) - 5))
    if problems:
        raise SystemExit(
            "构建中止：tools/ 下的脚本是单独运行、直接 print 到 CC 终端的，"
            "代码与字符串只允许 ASCII（注释不受限）。\n"
            "请把这些提示写成英文，不要用 \\uXXXX 转义（Lua 5.1 不会还原，会原样打印）：\n"
            + "\n".join(problems))
    print("tools 检查：通过（%d 个独立脚本，代码与字符串均为 ASCII）" % len(files))
    run_lua_syntax_check(files, base_dir)

def run_ascii_check(files, fix=False):



    ascii_source = load_ascii_checker()
    fixed = 0
    if fix:
        for rel, content in files:
            bad = ascii_source.find_violations(content)
            if not bad:
                continue
            converted = ascii_source.convert(content)
            if converted != content:
                path = os.path.join(BASE_DIR_HACK[0], rel.replace("/", os.sep))
                with open(path, "w", encoding="utf-8", newline="") as handle:
                    handle.write(converted)
                fixed += len(bad)
                print("  - 自动转换 %s：%d 处非 ASCII → \\uXXXX" % (rel, len(bad)))
        if fixed:
            files = [(rel, read_text(os.path.join(BASE_DIR_HACK[0], rel.replace("/", os.sep)))) for rel, _ in files]
            print("ASCII 检查：已自动修正 %d 处，源码已重新读取" % fixed)

    problems = []
    for rel, content in files:
        bad = ascii_source.find_violations(content)
        if not bad:
            continue
        problems.append("%s：%d 处非 ASCII（代码/字符串）" % (rel, len(bad)))
        for line, col, ch, kind in bad[:5]:
            problems.append("    第 %d 行第 %d 列 [%s] %r" % (line, col, kind, ch))
        if len(bad) > 5:
            problems.append("    ...（其余 %d 处省略）" % (len(bad) - 5))
    if problems:
        raise SystemExit(
            "构建中止：Lua 源码的代码/字符串部分只允许 ASCII，注释不受限。\n"
            "字符串里的中文请写成 \\uXXXX 字面转义，或直接运行：python build.py --fix-ascii\n"
            + "\n".join(problems)
        )
    print("ASCII 检查：通过（%d 个 Lua 文件，代码与字符串均为 ASCII）" % len(files))
    return files

def run_message_check(base_dir):
    root = repo_root(base_dir)
    tools_dir = os.path.join(root, "tools")
    if not os.path.isfile(os.path.join(tools_dir, "check_messages.py")):
        raise SystemExit("构建中止：找不到 tools/check_messages.py（文案一致性检查脚本）")
    sys.path.insert(0, tools_dir)
    import importlib
    checker = importlib.import_module("check_messages")
    problems = []
    keys = checker.backend_keys()
    zh = checker.frontend_keys("zh", "MSG")
    en = checker.frontend_keys("en", "MSG")
    checker.compare("MSG.zh（键名定义见 backend/modules/message.lua）", keys, zh, problems)
    checker.compare("MSG.en（frontend/web/ifm-messages.js）", zh, en, problems)
    checker.compare_placeholders("MSG", checker.frontend_placeholders("zh", "MSG"),
                                 checker.frontend_placeholders("en", "MSG"), problems)
    izh = checker.frontend_keys("zh", "I18N")
    ien = checker.frontend_keys("en", "I18N")
    checker.compare("I18N.en（frontend/web/ifm-messages.js）", izh, ien, problems)
    checker.compare_placeholders("I18N", checker.frontend_placeholders("zh", "I18N"),
                                 checker.frontend_placeholders("en", "I18N"), problems)
    for rel, number, bad in checker.frontend_issues():
        problems.append("  前端注释之外出现非 ASCII：%s:%d  %s" % (rel, number, bad))
    pending = []
    for path in checker.source_files():
        with open(path, "r", encoding="utf-8") as handle:
            count = checker.count_escapes(handle.read())
        if count:
            pending.append("%s=%d" % (os.path.relpath(path, root).replace(os.sep, "/"), count))
    if pending:
        problems.append("  运行期 Lua 里还有硬编码的 unicode 转义（应改用 Message.KEYS）：%s"
                        % ", ".join(pending))
    if problems:
        raise SystemExit(
            "构建中止：文案检查未通过。\n" + "\n".join("    " + line for line in problems) +
            "\n修法：文案写进 frontend/web/ifm-messages.js 的 MSG（服务端消息，键名同时要在 "
            "backend/modules/message.lua 的 Message.KEYS 里）或 I18N（界面文案）；日志一律英文。")
    print("文案检查：通过（后端 %d 键 -> MSG.zh %d -> MSG.en %d；I18N %d/%d 双语一致；前端注释外无非 ASCII）"
          % (len(keys), len(zh), len(en), len(izh), len(ien)))


def build_bundle(base_dir, output_path, keep_comments=False, fix_ascii=False, version=None):
    BASE_DIR_HACK[0] = base_dir
    modules, main_entry = collect_files(base_dir)
    extras = collect_extra_entries(base_dir)
    files = list(modules) + [main_entry] + extras
    files = run_ascii_check(files, fix_ascii)
    files = run_local_order_check(files)
    files = run_reserved_word_check(files)
    files = run_global_write_check(files)
    files = run_nil_call_arithmetic_check(files)
    files = run_method_shadow_check(files)
    files = run_hard_dependency_check(files)
    run_message_check(base_dir)
    files = run_lua_syntax_check(files)
    run_tools_check(base_dir)
    raw_size = sum(len(content.encode("utf-8")) for _, content in files)
    extra_count = len(extras)
    if not keep_comments:
        files = [(rel, strip_comments(content)) for rel, content in files]
        files = [(rel, strip_line_indentation(content)) for rel, content in files]
        files = run_lua_syntax_check(files)
    modules = files[:len(files) - 1 - extra_count]
    main_entry = files[len(files) - 1 - extra_count]
    stripped_size = sum(len(content.encode("utf-8")) for _, content in files)
    digest = hashlib.sha256()
    for rel, content in files:
        digest.update(rel.encode("utf-8"))
        digest.update(content.encode("utf-8"))
    archive_source, blob_size, encoded_size = render_archive(files)
    data = archive_source + render_vendor(base_dir)
    loop_source = ZIP_LOOP
    cleanup_source = "__IFM_ARCHIVE = nil"
    archive_size = (blob_size, encoded_size)
    parts = [
        HEADER.format(
            built_at=time.strftime("%Y-%m-%d %H:%M:%S"),
            digest=digest.hexdigest()[:16],
            version=str(version) if version is not None else "?",
        ),
        BOOTSTRAP_TEMPLATE.format(
            module_dir=MODULE_DIR_NAME,
            main=MAIN_FILE_NAME,
            worker=WORKER_FILE_NAME,
            crafter=CRAFTER_FILE_NAME,
            data=data,
            loop=loop_source,
            cleanup=cleanup_source,
        ),
    ]
    bundle = "".join(parts)
    if archive_size:
        print("载荷：ZIP %d 字节 -> base64 %d 字符（由内嵌 zzlib 在 CC:T 端解压）" %
              (archive_size[0], archive_size[1]))
    out_dir = os.path.dirname(os.path.abspath(output_path))
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(bundle)
    return files, len(bundle), raw_size, stripped_size

def strip_line_indentation(content):









    out = []
    index = 0
    size = len(content)
    at_line_start = True
    while index < size:
        match = LONG_BRACKET.match(content, index)
        if match:
            end = long_bracket_end(content, index, match.group(1))
            out.append(content[index:end])
            at_line_start = content[end - 1:end] == "\n"
            index = end
            continue
        char = content[index]
        if char == "\n":
            out.append(char)
            at_line_start = True
            index += 1
            continue
        if at_line_start and (char == " " or char == "\t"):
            index += 1
            continue
        at_line_start = False
        if char in "\"'":
            end = scan_short_string(content, index)
            out.append(content[index:end])
            index = end
            continue
        out.append(char)
        index += 1
    return "".join(out)

def strip_comments(content):













    parts = []
    index = 0
    size = len(content)
    last_was_string = False
    while index < size:
        char = content[index]
        if char in ("'", '"'):
            end = scan_short_string(content, index)
            parts.append(content[index:end])
            index = end
            last_was_string = True
            continue
        if char == "[":
            match = LONG_BRACKET.match(content, index)
            if match:
                end = long_bracket_end(content, index, match.group(1))
                parts.append(content[index:end])
                index = end
                last_was_string = True
                continue
            parts.append(char)
            index += 1
            last_was_string = False
            continue
        if char == "-" and content.startswith("--", index):
            match = LONG_BRACKET.match(content, index + 2)
            if match:
                end = long_bracket_end(content, index + 2, match.group(1))
                parts.append(re.sub(r"[^\n]", "", content[index:end]))
                index = end
                last_was_string = True
                continue
            newline = content.find("\n", index)
            index = size if newline < 0 else newline
            continue
        if char == "\n":
            if not last_was_string:
                trim_trailing_blanks(parts)
            parts.append(char)
            index += 1
            last_was_string = False
            continue
        parts.append(char)
        index += 1
        last_was_string = False
    if not last_was_string:
        trim_trailing_blanks(parts)
    return "".join(parts)

LONG_BRACKET = re.compile(r"\[(=*)\[")

def long_bracket_end(content, start, equals):
    closer = "]" + equals + "]"
    found = content.find(closer, start + 2 + len(equals))
    if found < 0:
        return len(content)
    return found + len(closer)

def scan_short_string(content, start):
    quote = content[start]
    index = start + 1
    size = len(content)
    while index < size:
        char = content[index]
        if char == "\\":
            index += 2
            continue
        if char == quote:
            return index + 1
        index += 1
    return size

def trim_trailing_blanks(parts):
    while parts:
        last = parts[-1]
        stripped = last.rstrip(" \t")
        if stripped:
            if stripped != last:
                parts[-1] = stripped
            return
        parts.pop()

def main(argv=None):
    parser = argparse.ArgumentParser(description="IFM 单文件构建脚本")
    parser.add_argument("-o", "--out", default=None, help="输出文件路径（默认与脚本同级的 %s）" % DEFAULT_OUTPUT)
    parser.add_argument("--keep-comments", "--minify-comments-off", dest="keep_comments", action="store_true",
                        help="保留源码注释（默认会全部剥离：产物要能塞进 CC:T 的小磁盘）")
    parser.add_argument("--fix-ascii", action="store_true",
                        help="发现非 ASCII 的代码/字符串时自动转成 \\uXXXX 再继续构建（默认报错中止）")
    parser.add_argument("--version", default=None, metavar="N",
                        help="指定本次构建的版本号（单一整数，例如 306）；默认每次构建自动 +1")
    parser.add_argument("--bump", action="store_true",
                        help="版本号 +1（现在这是**默认行为**，此参数保留兼容）")
    parser.add_argument("--no-bump", dest="no_bump", action="store_true",
                        help="不改版本号（只重新打包 bundle 时用）")
    args = parser.parse_args(argv)

    base_dir = os.path.dirname(os.path.abspath(__file__))
    current = read_version(base_dir)
    if args.version is not None:
        target = parse_version(args.version)
    elif args.no_bump:
        target = current
    else:
        target = current + 1
    if target != current:
        print("项目版本：%d -> %d" % (current, target))
    write_version(base_dir, target)
    output_path = args.out or os.path.join(base_dir, DEFAULT_OUTPUT)
    if os.path.basename(output_path).lower() in (MAIN_FILE_NAME.lower(), WORKER_FILE_NAME.lower(),
                                                 CRAFTER_FILE_NAME.lower()):
        print("警告：产物与 %s / %s / %s 同名，运行时会被保留（不自我删除）；它本身不是入口本体，建议换个名字。" %
              (MAIN_FILE_NAME, WORKER_FILE_NAME, CRAFTER_FILE_NAME))
    files, size, raw_size, stripped_size = build_bundle(base_dir, output_path, args.keep_comments,
                                                        args.fix_ascii, target)
    print("已生成单文件产物：%s" % output_path)
    print("内嵌文件 %d 个（含主入口）：" % len(files))
    for rel, content in files:
        print("  - %s (%d 字节)" % (rel, len(content.encode("utf-8"))))
    if not args.keep_comments:
        saved = raw_size - stripped_size
        print("注释剥离：源码 %d 字节 -> %d 字节（省下 %d 字节，%.0f%%）" %
              (raw_size, stripped_size, saved, (saved * 100.0 / raw_size) if raw_size else 0))
    print("产物总计 %d 字节（CC:T 默认磁盘 1MB，%s）" %
          (size, "放得下" if size < 1000000 else "可能放不下：请检查是否有超大文件或改用 --out 分卷"))
    print("版本号 %d 已写入 6 处：transfer.lua / IFMMaster.lua / ifm-core.js / ifm-app.js / "
          "index.html 的 data-ifm-build 与全部 ?v=。" % target)
    print("提示：产物只解压、不自启：运行后会在同级创建 ifm/ 目录，把 IFMMaster.lua / IFMWorker.lua / "
      "IFMCrafter.lua 与 modules/*.lua 写进去，并删除产物自身；")
    print("      然后手动运行 ifm/%s [--room <房间号>] [--relay <中转地址前缀>] [--random-room] 启动服务端。" % MAIN_FILE_NAME)
    print("      其它计算机（worker / 机械臂）用同一份产物解压后，启动 ifm/%s 或 ifm/%s 即可。"
          % (WORKER_FILE_NAME, CRAFTER_FILE_NAME))
    return 0

if __name__ == "__main__":
    sys.exit(main())
