#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""IFM 单文件构建脚本（位于 backend/）。

把本目录下的 backend/IFMMaster.lua 与 backend/ifm/*.lua 打包成一个独立的 Lua 文件
（默认 backend/ifm_bundle.lua）。
产物是一个**纯解压器**：运行时把内嵌的源码写回磁盘（IFMMaster.lua + ifm/*.lua），
**不会自启服务端**，并在解压完成后**删除自身**；之后手动运行 IFMMaster.lua 启动服务端。
因此既保留了“多文件模块化开发”，又方便整包复制进 CC:Tweaked 计算机后一次性拆包。

注意：产物**不要命名为 IFMMaster.lua**（同名时它会被当作服务端入口保留、不自我删除，
而且它是解压器而不是服务端本体）。

用法（一条命令完成全部检查与打包；在仓库根或 backend/ 下都能跑）：
  python backend/build.py                # 输出到 backend/ifm_bundle.lua（**默认剥离注释**）
  cd backend && python build.py          # 等价写法
  python backend/build.py -o dist/ifm_unpack.lua   # 指定输出路径
  python backend/build.py --keep-comments          # 保留源码注释（产物会大一倍以上，一般不要）
  python backend/build.py --fix-ascii              # 发现非 ASCII 时自动转成 \\uXXXX 后继续构建

产物默认**不带注释**：模块里的中文注释是体积大头（UTF-8 三字节一个字），
CC:Tweaked 计算机的磁盘很小（默认 1MB），带注释的产物会直接写不进去（"ifm_bundle: out of space"）。
剥离是 Lua 感知的（不会误伤字符串与 [[..]] 长字符串），并且剥离后会**再跑一次语法检查**；
产物解压出来的源码因此没有注释 —— 要看注释请直接用仓库里的 backend/ 源码。

构建流程里**强制**包含源码 ASCII 检查（不需要手动跑别的脚本）：
  * 代码部分（包括字符串字面量）只能是 ASCII；出现其他字符直接报错并中止构建。
  * 注释里可以放任意字符（中文说明不受影响）。
  * 字符串里的中文写成 \\uXXXX 字面转义即可，浏览器会还原成中文再显示：
        return false, "\\\\u540d\\\\u79f0\\\\u4e0d\\\\u80fd\\\\u4e3a\\\\u7a7a"   -- 名称不能为空
  * 想批量修正已有源码时用 --fix-ascii（等价于 python tools/ascii_source.py --write）。
"""

import argparse
import hashlib
import os
import re
import sys
import time

MODULE_DIR_NAME = "ifm"
MAIN_FILE_NAME = "IFMMaster.lua"
# 分布式工作节点入口（也会打进产物：解压后同一台机器上就能二选一启动；
# 计算机角色只取决于你启动哪个入口：ifm.lua = 主控，IFMWorker.lua = 工作节点）
WORKER_FILE_NAME = "IFMWorker.lua"
DEFAULT_OUTPUT = "ifm_bundle.lua"

HEADER = """-- IFM (Integrated Factory Manager) single-file unpacker
-- Generated by build.py at {built_at}; do not edit manually
-- (edit IFMMaster.lua / ifm/*.lua and rebuild). Fingerprint: {digest}
--
-- What it does (unpack only, no auto-start):
--   * writes the embedded sources back to disk next to this file:
--       ./IFMMaster.lua    (server entry - start it yourself afterwards)
--       ./ifm/*.lua        (modules; identical content is skipped)
--   * then deletes this bundle file itself
--     (unless this file is named IFMMaster.lua, in which case it is kept as the entry).
--
-- Usage (CC:Tweaked computer):
--   ifm_bundle                     (run this file once)
--   then start the server with:    IFMMaster.lua [--room <room>] [--relay <ws-base-url>] [--random-room]
--   arguments given to the bundle are ignored.
"""


def read_text(path):
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def collect_files(base_dir):
    """返回 [(相对路径, 内容), ...]，主程序放在最后"""
    modules = []
    module_dir = os.path.join(base_dir, MODULE_DIR_NAME)
    if not os.path.isdir(module_dir):
        raise SystemExit("找不到模块目录：%s" % module_dir)
    for name in sorted(os.listdir(module_dir)):
        if not name.endswith(".lua"):
            continue
        path = os.path.join(module_dir, name)
        rel = "%s/%s" % (MODULE_DIR_NAME, name)
        modules.append((rel, read_text(path)))
    if not modules:
        raise SystemExit("模块目录中没有 .lua 文件：%s" % module_dir)
    main_path = os.path.join(base_dir, MAIN_FILE_NAME)
    if not os.path.isfile(main_path):
        raise SystemExit("找不到主程序：%s" % main_path)
    main_rel = MAIN_FILE_NAME
    return modules, (main_rel, read_text(main_path))


def collect_extra_entries(base_dir):
    """除模块与主入口之外，还要一起打进产物的**独立入口文件**（解压后即可就地启动）。
    目前是 IFMWorker.lua：worker 计算机与主控计算机用的是同一份产物，角色只由启动的入口决定。"""
    out = []
    worker_path = os.path.join(base_dir, WORKER_FILE_NAME)
    if os.path.isfile(worker_path):
        out.append((WORKER_FILE_NAME, read_text(worker_path)))
    return out


def bracket_level_for(content):
    """根据内容选择合适的长括号等级，避免与内容里的 ]==] 冲突"""
    level = 1
    for match in re.finditer(r"\](=*)\]", content):
        level = max(level, len(match.group(1)) + 1)
    for match in re.finditer(r"\[(=*)\[", content):
        level = max(level, len(match.group(1)) + 1)
    return level


BOOTSTRAP_TEMPLATE = """
-- ===== Embedded sources: written next to this file =====
local __IFM_FILES = {{
{entries}}}

-- 同一路径的两种写法（"a/b.lua" 与 "/a/b.lua"）视为相等
local __ifm_normalizePath = function(path)
    local value = fs.combine(path)
    if value:sub(1, 1) == "/" and #value > 1 then
        value = value:sub(2)
    end
    return value
end

local __ifm_unpack = function()
    local program = (shell and shell.getRunningProgram and shell.getRunningProgram()) or "{main}"
    --- `wget run <url>` 时“正在运行的程序”在磁盘上并不存在（甚至可能是个 URL 字符串）：
    --- 这时就解包到 **shell 的当前目录**，不要拿一个不存在的路径去 fs.getDir（会解到奇怪的目录里）
    local baseDir
    if fs.exists(program) then
        baseDir = fs.getDir(program)
    elseif shell and shell.dir then
        baseDir = shell.dir()
    else
        baseDir = fs.getDir(program)
    end
    if baseDir == "" then
        baseDir = "/"
    end
    local programPath = __ifm_normalizePath(program)
    local created, updated, unchanged, skipped = 0, 0, 0, 0
    for relative, content in pairs(__IFM_FILES) do
        local path = fs.combine(baseDir, relative)
        if __ifm_normalizePath(path) == programPath then
            -- do not overwrite the file that is currently running
            skipped = skipped + 1
        else
            local folder = fs.getDir(path)
            if folder ~= "" and not fs.exists(folder) then
                fs.makeDir(folder)
            end
            local current = nil
            if fs.exists(path) then
                local handle = fs.open(path, "r")
                if handle then
                    current = handle.readAll()
                    handle.close()
                end
            end
            if current == content then
                unchanged = unchanged + 1
            else
                local handle = fs.open(path, "w")
                if not handle then
                    error("Cannot write " .. path, 0)
                end
                handle.write(content)
                handle.close()
                if current then
                    updated = updated + 1
                else
                    created = created + 1
                end
            end
        end
    end
    print(("[IFM] unpack: %d created, %d updated, %d unchanged, %d skipped"):format(
        created, updated, unchanged, skipped))
    print("[IFM] entry file: " .. fs.combine(baseDir, "{main}"))
    return baseDir
end

-- ===== 解压（本产物只解压，不会自启服务端） =====
local __ifm_base = __ifm_unpack()
__IFM_FILES = nil

if select("#", ...) > 0 then
    print("[IFM] note: this bundle only unpacks; arguments are ignored (pass them to IFMMaster.lua)")
end

-- ===== 解压完成后删除本产物自身 =====
local __ifm_self = (shell and shell.getRunningProgram and shell.getRunningProgram()) or nil
local __ifm_entry = __ifm_normalizePath(fs.combine(__ifm_base, "{main}"))
if __ifm_self == nil then
    print("[IFM] warning: cannot locate this file, please delete it manually")
elseif not fs.exists(__ifm_self) then
    -- `wget run <url>` / `pastebin run ...` 这类“直接从 URL 跑”的情况：磁盘上根本没有这个文件，
    -- 没有东西可删（也不要打印“删不掉”的警告）。（1.6.13）
    print("[IFM] this bundle was run from a URL (no file on disk): nothing to delete")
elseif __ifm_normalizePath(__ifm_self) == __ifm_entry
    or __ifm_normalizePath(__ifm_self) == __ifm_normalizePath(fs.combine(__ifm_base, "{worker}")) then
    -- 本产物被命名为 ifm.lua / IFMWorker.lua：它就是入口文件本身，不能删除自己
    print("[IFM] this file is named {main} or {worker}, keeping it (it is an entry point, not the unpacker)")
else
    local okDelete, deleteErr = pcall(fs.delete, __ifm_self)
    if okDelete then
        print("[IFM] unpacker deleted: " .. fs.combine(__ifm_self))
    else
        print("[IFM] warning: could not delete " .. fs.combine(__ifm_self) .. " (" .. tostring(deleteErr) .. ")")
    end
end

print("[IFM] unpack finished - the server was NOT started by this file.")
print("[IFM] start it with: {main} [--room <room>] [--relay <ws-base-url>] [--random-room]")
"""


def render_entries(files):
    chunks = []
    for rel, content in files:
        level = bracket_level_for(content)
        opener = "[" + "=" * level + "["
        closer = "]" + "=" * level + "]"
        chunks.append('    ["%s"] = %s\n%s%s,\n' % (rel, opener, content, closer))
    return "".join(chunks)


def load_ascii_checker():
    """载入 tools/ascii_source.py（用于“代码与字符串必须是 ASCII”的检查）。

    本脚本位于 backend/，而检查工具在仓库根的 tools/ 下；为了兼容不同摆放方式，
    这里依次尝试几个候选位置（脚本同级 tools/、上一层 tools/、上两层 tools/）。
    """
    here = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        os.path.join(here, "tools"),
        os.path.join(os.path.dirname(here), "tools"),
        os.path.join(os.path.dirname(os.path.dirname(here)), "tools"),
    ]
    for tools_dir in candidates:
        if os.path.isfile(os.path.join(tools_dir, "ascii_source.py")):
            if tools_dir not in sys.path:
                sys.path.insert(0, tools_dir)
            import ascii_source
            return ascii_source
    raise SystemExit("找不到检查工具 tools/ascii_source.py（已尝试：%s）" % "、".join(candidates))


# 自动转换时需要用到的仓库根目录（build_bundle 里按实际 base_dir 设置）
BASE_DIR_HACK = [os.path.dirname(os.path.abspath(__file__))]

# Lua 保留字不能当字段名 / 表键：`t.local = 1`、`{ local = 0 }` 都是 Lua 5.1 的语法错误
# （CC:T 会直接报 “unexpected symbol near 'local'”，而且这种错误只有真正 load 时才暴露）。
LUA_KEYWORDS = (
    "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
    "if", "in", "local", "nil", "not", "or", "repeat", "return", "then",
    "true", "until", "while",
)
KEYWORD_FIELD_PATTERNS = (
    ("字段访问 t.<关键字>", re.compile(r"\.\s*(%s)\b" % "|".join(LUA_KEYWORDS))),
    ("表键 { <关键字> =", re.compile(r"[,{]\s*(%s)\s*=" % "|".join(LUA_KEYWORDS))),
)
STRING_LITERAL = re.compile(r"\"(\\\\.|[^\"\\\\])*\"|'(\\\\.|[^'\\\\])*'")


# 实例字段把类方法遮蔽掉：`function Diagnose:perf()` 定义了方法 perf，
# 而 `diagnose.perf = <表>`（或同一文件里的 `self.perf = <表>`）会在实例上放一个同名字段；
# 之后 `obj:perf()` 就会报 “attempt to call method 'perf' (a table value)”。
METHOD_DEF = re.compile(r"^\s*function\s+([A-Za-z0-9_]+)\s*[:.]\s*([A-Za-z0-9_]+)\s*\(")
FIELD_ASSIGN = re.compile(r"^\s*([A-Za-z0-9_.]+)\s*\.\s*([A-Za-z0-9_]+)\s*=(?!=)")


def run_method_shadow_check(files):
    """检查“实例字段有没有把类方法遮蔽掉”（只有运行时才暴露，构建阶段先拦住）。"""
    methods, owners = {}, {}
    for rel, content in files:
        for line in content.splitlines():
            match = METHOD_DEF.match(line)
            if not match:
                continue
            class_name, method = match.group(1), match.group(2)
            methods.setdefault(class_name, set()).add(method)
            owners.setdefault(rel, set()).add(class_name)
    problems = []
    for rel, content in files:
        local_classes = owners.get(rel, set())
        for index, line in enumerate(content.splitlines(), 1):
            match = FIELD_ASSIGN.match(line.split("--")[0])
            if not match:
                continue
            target, field = match.group(1), match.group(2)
            last = target.split(".")[-1]
            if last == "self":
                candidates = local_classes
            else:
                candidates = set(name for name in methods if name.lower() == last.lower())
            for class_name in candidates:
                if field in methods.get(class_name, ()):
                    problems.append("  %s:%d  %s.%s 会覆盖 %s:%s()：%s" % (
                        rel, index, target, field, class_name, field, line.strip()[:90]))
    if problems:
        raise SystemExit(
            "构建中止：实例字段与类方法重名（运行时会报 attempt to call method 'x'）。\n"
            "请给字段改名（例如 perf -> perfStats、stats -> statsSummary）：\n" + "\n".join(problems)
        )
    print("方法遮蔽检查：通过（%d 个 Lua 文件，没有实例字段覆盖类方法）" % len(files))
    return files


# ===== 轻量 Lua 语法检查 =====
# 说明：这里不是完整的 Lua 解析器（本机没有 lua/luajit 可执行文件），
# 但能挡住“只有真正 load 时才报错”的几类常见错误：
#   1) `:` 方法调用却忘了写参数（Lua: function arguments expected / unexpected symbol）
#      —— 例如 `self:method and x`（正确写法是 `self.method and self:method()`）
#   2) 块结构不平衡（function/if/do/repeat 与 end/until 对不上，或提前多出一个 end）
#   3) 字符串没有收尾（换行前没闭合的 " 或 '）
LUA_METHOD_CALL = re.compile(r":\s*([A-Za-z_][A-Za-z_0-9]*)(?![A-Za-z_0-9])\s*(?![({}\"'])" + r"(?![A-Za-z_0-9])")


def strip_lua_code(content):
    """把注释、字符串、长括号替换成空格（保留换行），只留代码骨架；同时报告未闭合的字符串。"""
    out = []
    problems = []
    i = 0
    n = len(content)
    while i < n:
        match = re.match(r"\[(=*)\[", content[i:])
        if match:
            level = len(match.group(1))
            closer = "]" + "=" * level + "]"
            j = content.find(closer, i)
            j = n if j < 0 else j + len(closer)
            out.append("".join(" " if ch != "\n" else "\n" for ch in content[i:j]))
            i = j
            continue
        if content.startswith("--", i):
            j = content.find("\n", i)
            j = n if j < 0 else j
            out.append(" " * (j - i))
            i = j
            continue
        ch = content[i]
        if ch in "\"'":
            j = i + 1
            terminated = False
            while j < n:
                if content[j] == "\\":
                    j += 2
                    continue
                if content[j] == ch:
                    terminated = True
                    j += 1
                    break
                if content[j] == "\n":
                    break
                j += 1
            if not terminated:
                problems.append(("string", content.count("\n", 0, i) + 1, content[i:i + 60].split("\n")[0]))
            out.append(" " * (j - i))
            i = j
            continue
        out.append(ch)
        i += 1
    return "".join(out), problems


def run_lua_structure_check(files):
    """轻量结构检查（luaparse 不可用时的退路）：方法调用参数 / 块结构 / 字符串收尾。"""
    problems = []
    for rel, content in files:
        code, string_problems = strip_lua_code(content)
        for _, number, text in string_problems:
            problems.append("  %s:%d  字符串没有收尾：%s" % (rel, number, text.strip()[:60]))
        for match in LUA_METHOD_CALL.finditer(code):
            number = code.count("\n", 0, match.start()) + 1
            problems.append("  %s:%d  `:%s` 后面缺少调用参数（Lua 会报 function arguments expected）：%s"
                            % (rel, number, match.group(1),
                               code.split("\n")[number - 1].strip()[:80]))
        depth = 0
        for number, line in enumerate(code.split("\n"), 1):
            for word in re.findall(r"[A-Za-z_][A-Za-z_0-9]*", line):
                if word in ("function", "if", "do", "repeat"):
                    depth += 1
                elif word in ("end", "until"):
                    depth -= 1
                    if depth < 0:
                        problems.append("  %s:%d  多出来的 `end`（块结构已经回到顶层）：%s"
                                        % (rel, number, line.strip()[:80]))
                        depth = 0
        if depth != 0:
            problems.append("  %s  块结构不平衡：还差 %d 个 `end`/`until`" % (rel, depth))
    if problems:
        raise SystemExit(
            "构建中止：Lua 语法检查发现问题（这些错误只有真正 load 时才会暴露）。\n"
            "常见修法：`self:foo and x` -> `self.foo and self:foo()`；补齐/删掉多余的 end。\n"
            + "\n".join(problems)
        )
    print("Lua 结构检查：通过（%d 个 Lua 文件：方法调用参数 / 块结构 / 字符串收尾；建议装 luaparse 做完整语法检查）"
          % len(files))
    return files


# ===== Lua 语法检查（用现成库 luaparse；Lua 5.1 文法 = CC:T 用的 Lua）=====
# luaparse 是一个纯 JS 的 Lua 解析器（npm install luaparse），比手写的结构检查严格得多：
# 任何语法错误都会带行号报出来，和 CC:T 里 load 的行为一致（同一个 Lua 5.1 文法）。
LUAPARSE_RUNNER = r"""
const fs = require('fs');
const luaparse = require('luaparse');
const entries = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
let problems = 0;
for (const entry of entries) {
    try {
        luaparse.parse(entry.code, { luaVersion: '5.1', locations: true, comments: false, scope: false });
    } catch (err) {
        problems += 1;
        const line = err.line === undefined ? '?' : err.line;
        const message = String(err.message || err).split('\n')[0];
        console.log('  ' + entry.rel + ':' + line + '  ' + message);
    }
}
process.exit(problems ? 1 : 0);
"""


LUAPARSE_LAST_ERROR = [""]      # 最近一次探测 luaparse 失败的原因（构建时打印出来）
LUAPARSE_ENV = [None]           # 探测成功时用的环境（带 NODE_PATH），语法检查步骤复用


def luaparse_env(base_dir):
    """构造“能 require 到 luaparse”的环境变量：优先仓库里的 backend/node_modules，
    其次是上一层与 npm 全局目录。**必须把它同时交给探测与实际检查**：
    检查脚本写在临时目录里（%TEMP%），Node 只按脚本所在目录向上找 node_modules，
    看不到 backend/node_modules —— 以前只有探测带了这个环境，于是“探测通过、检查却
    报 Cannot find module 'luaparse'”，构建莫名其妙中止（错误还在 stderr 里被吞掉）。"""
    import os as _os

    env = dict(_os.environ)
    extra = [_os.path.join(base_dir, "node_modules"), _os.path.join(_os.path.dirname(base_dir), "node_modules")]
    try:
        import subprocess
        root = subprocess.run(["npm", "root", "-g"], capture_output=True, text=True, timeout=60)
        if root.returncode == 0 and root.stdout.strip():
            extra.append(root.stdout.strip())
    except Exception:
        pass
    env["NODE_PATH"] = _os.pathsep.join([p for p in extra if p] + [env.get("NODE_PATH", "")])
    return env


def luaparse_available(base_dir):
    """本机是否装了 Node 模块 luaparse（在当前环境里 require 得到就算有）。
    顺便把失败原因记进 LUAPARSE_LAST_ERROR、把环境记进 LUAPARSE_ENV。"""
    import subprocess

    env = luaparse_env(base_dir)
    try:
        result = subprocess.run(
            ["node", "-e", "process.stdout.write(require.resolve('luaparse'))"],
            cwd=base_dir, capture_output=True, text=True, timeout=120, env=env)
        if result.returncode == 0:
            LUAPARSE_ENV[0] = env
            return True
        LUAPARSE_LAST_ERROR[0] = (result.stderr or result.stdout or "").strip().splitlines()[-1][:160]
        return False
    except Exception as err:
        LUAPARSE_LAST_ERROR[0] = str(err)[:160]
        return False


def run_lua_syntax_check(files, base_dir=None):
    """Lua 语法检查：优先用现成的 luaparse，缺库时退回到轻量结构检查。"""
    import json
    import os as _os
    import subprocess
    import tempfile

    base_dir = base_dir or BASE_DIR_HACK[0]
    if not luaparse_available(base_dir):
        print("提示：没有找到 Node 模块 luaparse（原因：%s）——执行 npm install --prefix backend luaparse "
              "可启用完整 Lua 语法检查；本次退回轻量结构检查。" % (LUAPARSE_LAST_ERROR[0] or "unknown"))
        return run_lua_structure_check(files)

    runner_path = _os.path.join(tempfile.gettempdir(), "ifm_luaparse_check.js")
    payload_path = _os.path.join(tempfile.gettempdir(), "ifm_luaparse_files.json")
    with open(runner_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(LUAPARSE_RUNNER)
    with open(payload_path, "w", encoding="utf-8") as handle:
        # 直接带上源码（构建时文件内容本来就在内存里），不依赖磁盘路径
        json.dump([{"rel": rel, "code": content} for rel, content in files], handle)
    try:
        result = subprocess.run(["node", runner_path, payload_path],
                                cwd=base_dir, capture_output=True, text=True, timeout=600,
                                env=LUAPARSE_ENV[0] or luaparse_env(base_dir))
    except Exception as err:
        print("提示：luaparse 调用失败（%s），退回轻量结构检查。" % err)
        return run_lua_structure_check(files)
    if result.returncode != 0:
        # 明细在 stdout；脚本自己挂掉（例如找不到模块）时 stdout 是空的，这时把 stderr 也带上，
        # 否则构建只报一句“语法检查失败”，完全看不出发生了什么（以前就吃过这个亏）。
        details = (result.stdout or "").strip() or (result.stderr or "").strip() or "(没有输出)"
        raise SystemExit(
            "构建中止：Lua 语法检查失败（luaparse，Lua 5.1 文法 = CC:T 用的 Lua）。\n"
            "这些错误在 CC:T 里 load 时同样会报，请按行号修好再构建：\n" + details)
    print("Lua 语法检查：通过（luaparse，%d 个文件）" % len(files))
    return files


def run_reserved_word_check(files):
    """检查有没有把 Lua 保留字当字段名/表键（这是 Lua 5.1 语法错误，只有 load 时才报）。"""
    problems = []
    for rel, content in files:
        for index, line in enumerate(content.splitlines(), 1):
            code = line.split("--")[0]
            code = STRING_LITERAL.sub('""', code)      # 字符串字面量里的点不算字段访问
            for label, pattern in KEYWORD_FIELD_PATTERNS:
                if pattern.search(code):
                    problems.append("  %s:%d  %s：%s" % (rel, index, label, line.strip()[:100]))
    if problems:
        raise SystemExit(
            "构建中止：Lua 保留字被当成字段名/表键（Lua 5.1 语法错误，CC:T 会报 unexpected symbol）。\n"
            "请改名（例如 local -> localMoves）：\n" + "\n".join(problems)
        )
    print("保留字检查：通过（%d 个 Lua 文件，没有把保留字当字段名/表键）" % len(files))
    return files


def run_ascii_check(files, fix=False):
    """ASCII 检查（代码/字符串必须是 ASCII）——构建流程的强制步骤。

    返回检查结果说明；有违例且 fix=False 时直接中止构建。
    """
    ascii_source = load_ascii_checker()
    fixed = 0
    if fix:
        for rel, content in files:
            bad = ascii_source.find_violations(content)
            if not bad:
                continue
            converted = ascii_source.convert(content)
            if converted != content:
                path = os.path.join(BASE_DIR_HACK[0], rel.replace("/", os.sep))
                with open(path, "w", encoding="utf-8", newline="") as handle:
                    handle.write(converted)
                fixed += len(bad)
                print("  - 自动转换 %s：%d 处非 ASCII → \\uXXXX" % (rel, len(bad)))
        if fixed:
            files = [(rel, read_text(os.path.join(BASE_DIR_HACK[0], rel.replace("/", os.sep)))) for rel, _ in files]
            print("ASCII 检查：已自动修正 %d 处，源码已重新读取" % fixed)

    problems = []
    for rel, content in files:
        bad = ascii_source.find_violations(content)
        if not bad:
            continue
        problems.append("%s：%d 处非 ASCII（代码/字符串）" % (rel, len(bad)))
        for line, col, ch, kind in bad[:5]:
            problems.append("    第 %d 行第 %d 列 [%s] %r" % (line, col, kind, ch))
        if len(bad) > 5:
            problems.append("    ...（其余 %d 处省略）" % (len(bad) - 5))
    if problems:
        raise SystemExit(
            "构建中止：Lua 源码的代码/字符串部分只允许 ASCII，注释不受限。\n"
            "字符串里的中文请写成 \\uXXXX 字面转义，或直接运行：python build.py --fix-ascii\n"
            + "\n".join(problems)
        )
    print("ASCII 检查：通过（%d 个 Lua 文件，代码与字符串均为 ASCII）" % len(files))
    return files


def build_bundle(base_dir, output_path, keep_comments=False, fix_ascii=False):
    BASE_DIR_HACK[0] = base_dir
    modules, main_entry = collect_files(base_dir)
    # 主入口也一并内嵌：运行时会被解压回磁盘，便于以后直接运行 IFMMaster.lua
    # 额外入口（IFMWorker.lua）也打进去：同一台计算机的角色只取决于启动哪个入口
    extras = collect_extra_entries(base_dir)
    files = list(modules) + [main_entry] + extras
    # 构建流程内强制做 ASCII 检查（必要时可自动修正并继续）
    files = run_ascii_check(files, fix_ascii)
    # 再检查“保留字当字段名/表键”（Lua 5.1 语法错误，只有 load 时才暴露）
    files = run_reserved_word_check(files)
    # 最后检查“实例字段有没有把类方法遮蔽掉”（运行时报 attempt to call method 'x'）
    files = run_method_shadow_check(files)
    # Lua 语法检查（方法调用参数 / 块结构 / 字符串收尾）：本机没有 lua 可执行文件，这里是轻量替代
    files = run_lua_syntax_check(files)
    raw_size = sum(len(content.encode("utf-8")) for _, content in files)
    extra_count = len(extras)
    if not keep_comments:
        # **默认剥离全部注释**（所有内嵌文件，包括 IFMWorker.lua）：中文注释是产物体积的大头，
        # CC:T 磁盘放不下就会报 “ifm_bundle: out of space”。注释只影响可读性，不影响运行。
        files = [(rel, strip_comments(content)) for rel, content in files]
        # 剥离后的源码必须仍然是**合法 Lua**（防止剥离器误伤字符串 / 长字符串）：再过一遍语法检查
        files = run_lua_syntax_check(files)
    # 报告用：按顺序切回「模块 / 主入口 / 额外入口」
    modules = files[:len(files) - 1 - extra_count]
    main_entry = files[len(files) - 1 - extra_count]
    stripped_size = sum(len(content.encode("utf-8")) for _, content in files)
    digest = hashlib.sha256()
    for rel, content in files:
        digest.update(rel.encode("utf-8"))
        digest.update(content.encode("utf-8"))
    parts = [
        HEADER.format(
            built_at=time.strftime("%Y-%m-%d %H:%M:%S"),
            digest=digest.hexdigest()[:16],
        ),
        BOOTSTRAP_TEMPLATE.format(
            module_dir=MODULE_DIR_NAME,
            main=MAIN_FILE_NAME,
            worker=WORKER_FILE_NAME,
            entries=render_entries(files),
        ),
    ]
    # 注意：不再把主入口内容追加到产物末尾 —— 产物只负责解压（+ 自我删除），不自启服务端。
    bundle = "".join(parts)
    out_dir = os.path.dirname(os.path.abspath(output_path))
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(bundle)
    return files, len(bundle), raw_size, stripped_size


def strip_comments(content):
    """删掉 Lua 源码里**所有**注释（行注释 `--` 与块注释 `--[[ ]]`），保留其余内容与行数。

    为什么要这么做：模块里有大量中文注释（UTF-8 三个字节一个字），一起打进产物会让产物
    体积翻倍 —— CC:Tweaked 计算机的磁盘很小（默认 1MB），产物会直接写不进去
    （"ifm_bundle: out of space"）。注释是给读源码的人看的，跑起来不需要：
    产物解压出来的源码因此没有注释；要看注释请直接用仓库里的 backend/ 源码。

    正确处理（绝不会误伤代码）：
      * 短字符串 '...' / "..."（含 \\ 转义）；
      * 长字符串 [[...]] / [=[...]=]：Lua 里这是**代码**，原样保留；
      * 整行注释与行尾注释；
      * 块注释里的换行保留 —— 行号基本不变，产物里的报错仍然对得上源码；
      * 注释删掉后行尾留下的空白也一并清掉（产物更小），但绝不会动字符串内部。
    """
    parts = []
    index = 0
    size = len(content)
    last_was_string = False
    while index < size:
        char = content[index]
        if char in ("'", '"'):
            end = scan_short_string(content, index)
            parts.append(content[index:end])
            index = end
            last_was_string = True
            continue
        if char == "[":
            match = LONG_BRACKET.match(content, index)
            if match:
                end = long_bracket_end(content, index, match.group(1))
                parts.append(content[index:end])
                index = end
                last_was_string = True
                continue
            parts.append(char)
            index += 1
            last_was_string = False
            continue
        if char == "-" and content.startswith("--", index):
            match = LONG_BRACKET.match(content, index + 2)
            if match:
                # 块注释：只留下其中的换行（行号不变）
                end = long_bracket_end(content, index + 2, match.group(1))
                parts.append(re.sub(r"[^\n]", "", content[index:end]))
                index = end
                last_was_string = True          # 保留的换行后不算“行尾空白”
                continue
            newline = content.find("\n", index)
            index = size if newline < 0 else newline
            continue
        if char == "\n":
            if not last_was_string:
                trim_trailing_blanks(parts)
            parts.append(char)
            index += 1
            last_was_string = False
            continue
        parts.append(char)
        index += 1
        last_was_string = False
    if not last_was_string:
        trim_trailing_blanks(parts)
    return "".join(parts)


LONG_BRACKET = re.compile(r"\[(=*)\[")


def long_bracket_end(content, start, equals):
    """长括号（长字符串 / 块注释）的结束位置（含收尾的 ]==]）"""
    closer = "]" + equals + "]"
    found = content.find(closer, start + 2 + len(equals))
    if found < 0:
        return len(content)                     # 没闭合（源码本身有错）：留到结尾
    return found + len(closer)


def scan_short_string(content, start):
    """短字符串的结束位置（含收尾引号），\\ 转义按两个字符跳过"""
    quote = content[start]
    index = start + 1
    size = len(content)
    while index < size:
        char = content[index]
        if char == "\\":
            index += 2
            continue
        if char == quote:
            return index + 1
        index += 1
    return size


def trim_trailing_blanks(parts):
    """清掉 `parts` 末尾的行尾空白（注释被删后留下的空格/制表符）"""
    while parts:
        last = parts[-1]
        stripped = last.rstrip(" \t")
        if stripped:
            if stripped != last:
                parts[-1] = stripped
            return
        parts.pop()


def main(argv=None):
    parser = argparse.ArgumentParser(description="IFM 单文件构建脚本")
    parser.add_argument("-o", "--out", default=None, help="输出文件路径（默认与脚本同级的 %s）" % DEFAULT_OUTPUT)
    parser.add_argument("--keep-comments", "--minify-comments-off", dest="keep_comments", action="store_true",
                        help="保留源码注释（默认**会**全部剥离：产物要能塞进 CC:T 的小磁盘）")
    parser.add_argument("--fix-ascii", action="store_true",
                        help="发现非 ASCII 的代码/字符串时自动转成 \\uXXXX 再继续构建（默认报错中止）")
    args = parser.parse_args(argv)

    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = args.out or os.path.join(base_dir, DEFAULT_OUTPUT)
    if os.path.basename(output_path).lower() in (MAIN_FILE_NAME, WORKER_FILE_NAME.lower()):
        print("警告：产物与 %s / %s 同名，运行时会被保留（不自我删除）；它本身不是入口本体，建议换个名字。" %
              (MAIN_FILE_NAME, WORKER_FILE_NAME))
    files, size, raw_size, stripped_size = build_bundle(base_dir, output_path, args.keep_comments, args.fix_ascii)
    print("已生成单文件产物：%s" % output_path)
    print("内嵌文件 %d 个（含主入口）：" % len(files))
    for rel, content in files:
        print("  - %s (%d 字节)" % (rel, len(content.encode("utf-8"))))
    if not args.keep_comments:
        saved = raw_size - stripped_size
        print("注释剥离：源码 %d 字节 -> %d 字节（省下 %d 字节，%.0f%%）" %
              (raw_size, stripped_size, saved, (saved * 100.0 / raw_size) if raw_size else 0))
    print("产物总计 %d 字节（CC:T 默认磁盘 1MB，%s）" %
          (size, "放得下" if size < 1000000 else "**可能放不下**：请检查是否有超大文件或改用 --out 分卷"))
    print("提示：产物只解压、不自启：运行后会在同级目录写出 IFMMaster.lua 与 ifm/*.lua，并删除产物自身；")
    print("      然后手动运行 %s [--room <房间号>] [--relay <中转地址前缀>] [--random-room] 启动服务端。" % MAIN_FILE_NAME)
    return 0


if __name__ == "__main__":
    sys.exit(main())
